version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf  # 挂载配置文件
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  # 使用配置文件启动
